### ISSUE TITLE
Switch method fails for Python backend

### ISSUE THREAD

**Issue by bmwant** [thautwarm/Quick-Backend#2]
### Steps to reproduce

1. I'm trying to generate Python code for this Idris snippet (`check.idr` file)

```idris
sol : Nat -> List Nat -> Nat
sol k xs =
  length [1 | i <- zip [0..length xs] xs,
             j <- zip [0..length xs] xs,
              fst i < fst j,
              (snd i + snd j) `mod` k == 0]

main : IO ()
main = do fline <- getLine
          sline <- getLine
          let k = the Nat (cast (snd (span (/= ' ') fline)))
          let arr = [ the Nat (cast v) | v <- words sline ]
          printLn (sol k arr)
```

2. Codegeneration for QB

```
$ stack exec -- idris check.idr \
     -o check.qb \
     --codegen qb \
     --cg-opt "--javaname" \
     --cg-opt "--symemu" \
     -p quick-backend
```

3. Translating to Python code

```
$ python backend.py check.qb check.py
```

4. Running resulting code

```
$ python check.py
```

and I have the following error

```
Traceback (most recent call last):
  File "backend.py", line 176, in <module>
    wise(main)()
  File "/Users/bmwant/.pyenv/versions/idris-back/lib/python3.7/site-packages/wisepy2.py", line 117, in parse_arg
    return fn(*args, **kwargs)
  File "backend.py", line 165, in main
    for c in sum(Generate.read_and_gen(f), []):
  File "backend.py", line 153, in read_and_gen
    v = ctor(*args)
  File "backend.py", line 80, in Switch
    ret.append(sum(stmts, []))
TypeError: can only concatenate list (not "str") to list
```

### Issue

It seems to me that list comprehensions is being handled in a wrong way, but I'm not sure about it.

`Python 3.7.2`, `idris 1.3.2`, `stack 2.1.3`, quick backend `f92c1e77ea160f4786b596bddfc80850037e986c`

**Comment by thautwarm** [comment]
hello! sorry for the late response.
could you deliver the generated .qb file to me?
maybe via gist.

**Comment by thautwarm** [comment]
@bmwant

**Comment by bmwant** [comment]
@thautwarm here you go https://gist.github.com/bmwant/5811e55b2b604d43878484e10d632971. Thanks a lot, really appreciate your work

**Comment by thautwarm** [comment]
hi Misha, shall fix.
p.s: file io in each programming language is so awful..

**Comment by thautwarm** [comment]
@bmwant
